### ISSUE TITLE
Questions regarding GMD and OmniControl model differences

### ISSUE THREAD

**Issue by 2019211753** [neu-vi/OmniControl#13]
1. GMD suggests that using the ε model is more suitable for CG guidance. Could you please explain why OmniControl uses the x0 model, as demonstrated in your paper?
2. GMD converts the relative representation first, while OmniControl does so during the spatial guidance phase. Could you clarify the core difference? Is it related to efficiency, experimental effectiveness, or another factor?
Thank you very much for your assistance.

**Comment by ymingxie** [comment]
Hi,

Thanks for the interest in our work. 

1. OmniControl uses MDM as the base model, which uses x0 model. We didn't ablate between the x0 model and the epsilon model. It would be an interesting future work. 

2. The main difference is that GMD only handles the pelvis while OmniControl handles all joints. In addition, GMD converts sparse control signals to dense ones at the first stage, which might not be suitable for other joints because the relative position of other joints depends on the position of the pelvis and pelvis positions are unknown.

**Comment by 2019211753** [comment]
Thanks for your reply😊
